config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => "registrations",
    :omniauth_callbacks => "callbacks"
  }

  devise_scope :user do 
    get "login", to: "devise/sessions#new"
    get "signup", to: "devise/registrations#new"
  end

  resources :todo_lists do
    resources :todo_items do
    member do
    patch :complete
     end
    end
   end
  

  root 'application#welcome'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo_item.rb
class TodoItem < ApplicationRecord
  belongs_to :todo_list
  
def completed?
   !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ApplicationRecord
    has_many :todo_items, dependent: :delete_all
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/callbacks_controller.rb
class CallbacksController < Devise::OmniauthCallbacksController

    def github
        @user = User.from_omniauth(request.env["omniauth.auth"])
        if @user.persisted?
        sign_in_and_redirect @user
        else
        redirect_to new_user_registration_path
        end 
    end      
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    private

    def signup_params
        params
          .require(:user)
          .permit(:name, :email, :password, :password_confirmation)
    end

    def account_update_params
        params
          .require(:user)
          .permit(:name, :email, :password, :password_confirmation, current_password)
    end    
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :set_todo_list
  before_action :set_todo_item, except: [:create]
  def create
    @todo_item = @todo_list.todo_items.create(todo_item_params)
    redirect_to @todo_list
  end

  def destroy
    @todo_item = @todo_list.todo_items.find(params[:id])
    if @todo_item.destroy
    flash[:success] = "Todo List item was deleted."
    else
    flash[:error] = "Todo List item could not be deleted."
    end
    redirect_to @todo_list 
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to @todo_list, notice: "Todo item completed"
  end

  private

  def set_todo_list
    @todo_list = TodoList.find(params[:todo_list_id])
  end

  def set_todo_item
    @todo_item = @todo_list.todo_items.find(params[:id])
  end
  
  def todo_item_params
    params[:todo_item].permit(:content)
  end
 end

app/controllers/todo_lists_controller.rb
# class TodoListsController < ApplicationController
#   before_action :set_todo_list, only: %i[ show edit update destroy ]

#   # GET /todo_lists or /todo_lists.json
#   def index
#     @todo_lists = TodoList.all
#   end

 
#   # GET /todo_lists/1 or /todo_lists/1.json
#   def show
#   end

#   # GET /todo_lists/new
#   def new
#     @todo_list = TodoList.new
#   end

#   # GET /todo_lists/1/edit
#   def edit
#   end

#   # POST /todo_lists or /todo_lists.json
#   def create
#     @todo_list = TodoList.new(todo_list_params)

#     respond_to do |format|
#       if @todo_list.save
#         format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully created." }
#         format.json { render :show, status: :created, location: @todo_list }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @todo_list.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /todo_lists/1 or /todo_lists/1.json
#   def update
#     respond_to do |format|
#       if @todo_list.update(todo_list_params)
#         format.html { redirect_to todo_list_url(@todo_list), notice: "Todo list was successfully updated." }
#         format.json { render :show, status: :ok, location: @todo_list }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @todo_list.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /todo_lists/1 or /todo_lists/1.json
  
#   def destroy
#     @todo_list.destroy
#     respond_to do |format|
#       format.html { redirect_to todo_lists_url, notice: "Todo list was successfully destroyed." }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_todo_list
#       @todo_list = TodoList.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def todo_list_params
#       params.require(:todo_list).permit(:title, :description)
#     end

#     def destroy
#       @todo_list.destroy
#       respond_to do |format|
#         format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
#         format.json { head :no_content }
#       end
#     end

#   end
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render :show, status: :created, location: @todo_list }
      else
        format.html { render :new }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_list }
      else
        format.html { render :edit }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/views/application/welcome.html.erb
<style>
    h1 {
      text-align: center;
      
   }

   p {
     text-align: center;
     color: white
   }
</style>

    <div class="center">
  <h1 style = 'color: white'>WELCOME TO MARVEL LOUNGE</h1>
  <p> A place where you can keep track of your favorite Marvel films or shows so you never miss one</p>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Marvel Lounge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css'>
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  </head>
 <nav class="navbar navbar-expand-md navbar-light">
      <% if user_signed_in? %>
        <a class="navbar-brand" <%= link_to "Create List", todo_lists_path, method: :get %></a>
      <% else %>
        <a class="navbar-brand" <%= link_to "Marvel Lounge", root_path, method: :get %></a>
      <% end %>
         <ul>
              <% if user_signed_in? %>
               <li>   <a class="nav-item nav-link" <%= link_to "Logout", destroy_user_session_path, method: :delete  %></a> </li>
              <% else %>
               <li>   <a class="nav-item nav-link" <%= link_to "Login", new_user_session_path, method: :get %></a></li>
              <li>    <a class="nav-item nav-link" <%= link_to "Signup", new_user_registration_path, method: :get %></a></li>
                <li>   <a class="nav-item nav-link" <%= link_to "Sign in with GitHub", user_github_omniauth_authorize_path, method: :post %></a> </li>
                </ul>
              <% end %>
            </div>
          </div>
    </nav>
     
     <body> 
    <%= yield %>
    </body>
</html>

app/views/todo_items/_form.html.erb
<div class="listcontainer">
<%= form_for([@todo_list, @todo_list.todo_items.build]) do |f| %>
 <%= f.text_field :content, placeholder: "Add film or TV Show" %>
 <%= f.submit "Add to Watch List" %>
<% end %>
</div>

app/views/todo_items/_todo_item.html.erb
<!--- 
<p><%= todo_item.content %></p>
<%= link_to "Delete", todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } %>
<%= link_to "Mark as Complete", complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
-->
<div class="row clearfix">
 <% if todo_item.completed? %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i style="opacity: 0.4;" class="fa fa-check"></i>
   <% end %>
  </div>
  <div class="todo_item">
   <p style="opacity: 0.4;"><strike><%= todo_item.content %></strike></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
  </div>
 <% else %>
  <div class="complete">
   <%= link_to complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch do %>
    <i class="fa fa-circle-thin"></i>
   <% end %>
  </div>
  <div class="todo_item">
   <p><%= todo_item.content %></p>
  </div>
  <div class="trash">
   <%= link_to todo_list_todo_item_path(@todo_list, todo_item.id), method: :delete, data: { confirm: "Are you sure?" } do %>
    <i class="fa fa-trash"></i>
   <% end %>
  </div>
 <% end %>
</div>

app/views/todo_lists/_form.html.erb
<div class="listcontainer">
<%= form_with(model: todo_list) do |form| %>
  <% if todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>

      <ul>
        <% todo_list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="actions">
    <%= form.submit "Add Watch List" %>
  </div>
<% end %>
</div>

app/views/todo_lists/edit.html.erb
<h1 class="todo_list_title">Editing Todo List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Cancel', todo_lists_path %>
</div>

app/views/todo_lists/index.html.erb
<style>
    h1 {
      text-align: center;
      color: white;
   }
</style>
<div class="listcontainer">
<h1>Watch Lists</h1>
<p id="notice"><%= notice %></p>
<% @todo_lists.each do |todo_list| %>
<div class="index_row clearfix">
  <h2 class="todo_lists_title"><%= link_to todo_list.title, todo_list %></h2>
  <p class="todo_list_sub_title"><%= todo_list.description %></p>
</div>
<% end %>
<div class="links">
  <%= link_to "New Watch List", new_todo_list_path %>
</div>

app/views/todo_lists/new.html.erb
<h1 class="todo_list_title">Add Watch List</h1>
<div class="forms">
<%= render 'form', todo_list: @todo_list %>
</div>
<div class="links">
<%= link_to 'Back', todo_lists_path %>
</div>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>
<h2 class="todo_list_title"><%= @todo_list.title %></h2>
<p class="todo_list_sub_title"><%= @todo_list.description %></p>
<div id="todo_items_wrapper">
 <%= render @todo_list.todo_items %>
 <div id="form">
  <%= render "todo_items/form" %>
 </div>
</div>
<div class="links">
 <%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
 <%= link_to 'Delete', todo_list_path(@todo_list), method: :delete, data: { confirm: "Are you sure?" } %> |
 <%= link_to 'Back', todo_lists_path %>
</div>